# This is the name of the workflow as it will appear in the Actions tab
name: Daily Commit

on:
  schedule:
    # This runs the workflow at 05:30 UTC every day
    # (min hour day-of-month month day-of-week)
    - cron: '30 5 * * *'
  
  # This line allows you to manually trigger the workflow from the GitHub UI
  # which is required for your testing step.
  workflow_dispatch:

jobs:
  daily_commit_job:
    # Run the job on the latest available GitHub-hosted runner
    runs-on: ubuntu-latest
    
    # Define the permissions required for this job
    # We need 'contents: write' to be able to push a commit
    permissions:
      contents: write

    steps:
      # Step 1: Check out the repository code
      # This is necessary for the workflow to access the repo.
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          # We need to fetch the full history to be able to push a commit
          fetch-depth: 0

      # Step 2: A step with your email in the name, as requested
      - name: 'Run by 24f2008306@ds.study.iitm.ac.in'
        run: echo "This step is identified by the user's email. Starting commit task..."

      # Step 3: Configure Git, create an empty commit, and push it
      - name: Create and push daily commit
        run: |
          # Configure the Git user for this commit
          git config user.name "GitHub Actions Bot"
          git config user.email "github-actions-bot@users.noreply.github.com"
          
          # Get the current branch name (e.g., 'main' or 'master')
          BRANCH=$(git rev-parse --abbrev-ref HEAD)
          
          echo "Running on branch $BRANCH"
          
          # Create an empty commit with a message
          # The --allow-empty flag is crucial. It creates a new commit
          # even if no files have changed, guaranteeing a commit on every run.
          git commit --allow-empty -m "Automated daily commit"
          
          # Push the new commit to the origin repository on the current branch
          git push origin $BRANCH
